$schema: https://json-schema.org/draft/2020-12/schema
description: Data quality metrics
type: object
properties:
  accuracy_days:
    type: number
  bias_days:
    type: number
  validation_method:
    type: string
  known_limitations:
    type: array
    items:
      type: string
