$schema: https://json-schema.org/draft/2020-12/schema
description: CoverageJSON NdArray - n-dimensional data array
type: object
required: [type, dataType, axisNames, shape]
properties:
  type:
    type: string
    const: NdArray
  dataType:
    type: string
    enum: [integer, float, string]
  axisNames:
    type: array
    items: {type: string}
  shape:
    type: array
    items: {type: integer}
  values:
    type: array
